DROP TABLE IF EXISTS signedup_users;
CREATE TABLE signedup_users(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(25) DEFAULT NULL,
  contact_no VARCHAR(25) DEFAULT NULL,
  address VARCHAR(250) DEFAULT NULL
);
DROP TABLE IF EXISTS user;
  
CREATE TABLE user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  password VARCHAR(250) DEFAULT NULL
);
DROP TABLE IF EXISTS role;
CREATE TABLE role (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) DEFAULT NULL
  
); 

DROP TABLE IF EXISTS users_roles;
CREATE TABLE users_roles (
  user_id VARCHAR(250) DEFAULT NULL,
  role_id VARCHAR(250) DEFAULT NULL
  
);  
  
  
  